# Generated by Django 5.2.1 on 2025-05-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
