# Generated by Django 5.2.1 on 2025-05-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inscriptions', '0002_alter_etudiant_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=7)),
                ('duree', models.CharField(max_length=50)),
                ('resume', models.TextField()),
            ],
        ),
    ]
